export default {
	meta: {
		rights: [],
		heartbeats: [],
		already_seens: [],
		wishlists: [],
		likes: [],
		warnings: [],
	},
	data: {
		type: 'movies',
		id: 'matrix',
		numerical_id: 79,
		title: 'Matrix',
		original_title: 'The Matrix',
		year: 1999,
		short_plot:
			'Neo es el nick en la red que un aparentemente tranquilo trabajador deuna empresa de software utiliza en sus pirateos informáticos varios. Su doble vida se ve alterada cuando unas misteriosas frases aparecen en su ordenador: "Matrix te posee".',
		plot:
			'Neo es el nick en la red que un aparentemente tranquilo trabajador de una empresa de software utiliza en sus pirateos informáticos varios. Su doble vida se ve alterada cuando unas misteriosas frases aparecen en su ordenador: "Matrix te posee". Neo entabla contacto telefónico con el que cree que es otro hacker (Morfeo) y unos misteriosos agentes comienzan a seguirle. Toda la concepción de la vida que tenía se irá al traste cuando Morfeo le explica que lo que realmente está viviendo no es más que un largo sueño apoyado en realidades virtuales y que no vive en el siglo que cree.',
		duration: 136,
		highlight: '',
		duration_in_seconds: 8180,
		ultraviolet_enabled: false,
		groups: [],
		actors: [
			{
				type: 'people',
				id: 'keanu-reeves',
				numerical_id: 1034,
				photo: 'https://images-0.wuaki.tv/system/photos/1034/original/keanu-reeves-1525276036.jpeg',
				name: 'Keanu Reeves',
				born_at: null,
			},
			{
				type: 'people',
				id: 'laurence-fishburne',
				numerical_id: 1035,
				photo: 'https://images-1.wuaki.tv/system/photos/1035/original/laurence-fishburne-1525276037.jpeg',
				name: 'Laurence Fishburne',
				born_at: null,
			},
			{
				type: 'people',
				id: 'carrie-anne-moss',
				numerical_id: 1036,
				photo: 'https://images-0.wuaki.tv/system/photos/1036/original/carrie-anne-moss-1525276038.jpeg',
				name: 'Carrie-Anne Moss',
				born_at: null,
			},
			{
				type: 'people',
				id: 'hugo-weaving',
				numerical_id: 1037,
				photo: 'https://images-0.wuaki.tv/system/photos/1037/original/hugo-weaving-1525276041.jpeg',
				name: 'Hugo Weaving',
				born_at: null,
			},
			{
				type: 'people',
				id: 'gloria-foster',
				numerical_id: 1038,
				photo: 'https://images-0.wuaki.tv/system/photos/1038/original/gloria-foster-1525276041.jpeg',
				name: 'Gloria Foster',
				born_at: null,
			},
			{
				type: 'people',
				id: 'joe-pantoliano',
				numerical_id: 739,
				photo: 'https://images-0.wuaki.tv/system/photos/739/original/joe-pantoliano-1525275666.jpeg',
				name: 'Joe Pantoliano',
				born_at: null,
			},
			{
				type: 'people',
				id: 'marcus-chong',
				numerical_id: 1039,
				photo: 'https://images-1.wuaki.tv/system/photos/1039/original/marcus-chong-1525276043.jpeg',
				name: 'Marcus Chong',
				born_at: null,
			},
			{
				type: 'people',
				id: 'julian-arahanga',
				numerical_id: 1040,
				photo: 'https://images-3.wuaki.tv/system/photos/1040/original/julian-arahanga-1525276044.jpeg',
				name: 'Julian Arahanga',
				born_at: null,
			},
			{
				type: 'people',
				id: 'matt-doran',
				numerical_id: 1041,
				photo: 'https://images-0.wuaki.tv/system/photos/1041/original/matt-doran-1525276046.jpeg',
				name: 'Matt Doran',
				born_at: null,
			},
			{
				type: 'people',
				id: 'belinda-mcclory',
				numerical_id: 1042,
				photo: 'https://images-1.wuaki.tv/system/photos/1042/original/belinda-mcclory-1525276046.jpeg',
				name: 'Belinda McClory',
				born_at: null,
			},
			{
				type: 'people',
				id: 'anthony-ray-parker',
				numerical_id: 1043,
				photo: 'https://images-1.wuaki.tv/system/photos/1043/original/anthony-ray-parker-1525276048.jpeg',
				name: 'Anthony Ray Parker',
				born_at: null,
			},
			{
				type: 'people',
				id: 'paul-goddard',
				numerical_id: 1044,
				photo: 'https://images-2.wuaki.tv/system/photos/1044/original/paul-goddard-1525276050.jpeg',
				name: 'Paul Goddard',
				born_at: null,
			},
			{
				type: 'people',
				id: 'robert-taylor',
				numerical_id: 1045,
				photo: 'https://images-1.wuaki.tv/system/photos/1045/original/robert-taylor-1525276050.jpeg',
				name: 'Robert Taylor',
				born_at: null,
			},
			{
				type: 'people',
				id: 'david-aston',
				numerical_id: 1046,
				photo: 'https://images-2.wuaki.tv/system/photos/1046/original/david-aston-1525276052.jpeg',
				name: 'David Aston',
				born_at: null,
			},
			{
				type: 'people',
				id: 'marc-aden',
				numerical_id: 1047,
				photo: 'https://images-3.wuaki.tv/system/photos/1047/original/marc-aden-1525276054.jpeg',
				name: 'Marc Aden',
				born_at: null,
			},
		],
		awards: [
			{
				type: 'awardings',
				id: '1583',
				numerical_id: 1583,
				name: 'Oscar',
				description: '',
				year: 1999,
				category: 'Mejor montaje',
				result: 'Ganador',
				verdict: {
					name: 'winner',
					localized_name: 'Ganador',
				},
				photo: 'https://images-1.wuaki.tv/system/photos/1/original/oscar.jpg',
			},
			{
				type: 'awardings',
				id: '1597',
				numerical_id: 1597,
				name: 'Oscar',
				description: '',
				year: 1999,
				category: 'Mejor sonido',
				result: 'Ganador',
				verdict: {
					name: 'winner',
					localized_name: 'Ganador',
				},
				photo: 'https://images-1.wuaki.tv/system/photos/1/original/oscar.jpg',
			},
			{
				type: 'awardings',
				id: '1611',
				numerical_id: 1611,
				name: 'Oscar',
				description: '',
				year: 1999,
				category: 'Mejores efectos visuales',
				result: 'Ganador',
				verdict: {
					name: 'winner',
					localized_name: 'Ganador',
				},
				photo: 'https://images-1.wuaki.tv/system/photos/1/original/oscar.jpg',
			},
		],
		classification: {
			type: 'classifications',
			id: '5',
			numerical_id: 5,
			name: '18',
			age: 18,
			adult: false,
			description: 'Mostrar todos los contenidos, excluyendo los clasificados para adultos',
			default: true,
		},
		countries: [
			{
				type: 'countries',
				id: 'australia',
				numerical_id: 9,
				name: 'Australia',
			},
			{
				type: 'countries',
				id: 'united-states',
				numerical_id: 3,
				name: 'Estados Unidos',
			},
		],
		deep_links: {},
		extras: [],
		directors: [
			{
				type: 'people',
				id: 'lilly-wachowski',
				numerical_id: 827,
				photo: 'https://images-0.wuaki.tv/system/photos/827/original/andy-wachowski-1525275792.jpeg',
				name: 'Lilly Wachowski',
				born_at: null,
			},
			{
				type: 'people',
				id: 'lana-wachowski',
				numerical_id: 828,
				photo: 'https://images-2.wuaki.tv/system/photos/828/original/lana-wachowski-1525275794.jpeg',
				name: 'Lana Wachowski',
				born_at: null,
			},
		],
		genres: [
			{
				type: 'genres',
				id: 'accion',
				numerical_id: 35,
				name: 'Acción',
				adult: false,
				erotic: false,
				additional_images: {
					icon: 'https://images-2.wuaki.tv/system/brandable_photos/6231/original/1453732413-1453732413.png',
				},
			},
			{
				type: 'genres',
				id: 'ciencia-ficcion',
				numerical_id: 25,
				name: 'Ciencia ficción',
				adult: false,
				erotic: false,
				additional_images: {
					icon: 'https://images-0.wuaki.tv/system/brandable_photos/6354/original/1461243145-1461243145.png',
				},
			},
		],
		images: {
			artwork: 'https://images-1.wuaki.tv/system/artworks/79/master/matrix-1558427169.jpeg',
			snapshot: 'https://images-0.wuaki.tv/system/shots/1790/original/matrix-1480332860.jpeg',
			ribbons: [
				{
					type: 'ribbons',
					id: '6',
					numerical_id: 6,
					name: 'UHD',
					color: '#ffcc00',
					text_color: '#000000',
					position: 'top-left',
					localized_name: 'UHD',
					image: 'https://images-1.wuaki.tv/system/images/6/original/uhd-1418228576.png',
				},
			],
		},
		offline_enabled_for_est: true,
		offline_enabled_for_rent: true,
		offline_enabled_for_svod: false,
		order_options: [
			{
				type: 'order_options',
				id: '644924',
				numerical_id: 644924,
				legacy_instance_type: null,
				legacy_instance_id: null,
				periodic_points_reward_amount: 0,
				price: '3,99 €',
				price_without_currency: 3.99,
				points: {
					cost: 399,
					reward: 3,
				},
				purchase_type: {
					type: 'purchase_types',
					id: '1',
					numerical_id: 1,
					is_recurring: false,
					name: 'Alquiler 48H',
					label: 'ALQUILER 48H',
					kind: 'rental',
					expires_after_in_seconds: 172800,
					available_time_in_seconds: 172800,
				},
				video_quality: {
					type: 'video_qualities',
					id: 'SD',
					numerical_id: 2,
					name: 'SD',
					abbr: 'SD',
					position: 0,
					image: 'https://images-1.wuaki.tv/system/logos/2/original/sd-1456155688.png',
				},
				external_tiers: [
					{
						type: 'microsoft_store',
						id: '9P30JJT99V5D',
						price: '4,49 €',
					},
					{
						type: 'itunes',
						id: 'tv.wuaki.alternatetier3',
						price: '3,99 €',
					},
				],
				warnings: [],
				order_option_display_info: {},
			},
			{
				type: 'order_options',
				id: '644623',
				numerical_id: 644623,
				legacy_instance_type: null,
				legacy_instance_id: null,
				periodic_points_reward_amount: 0,
				price: '3,99 €',
				price_without_currency: 3.99,
				points: {
					cost: 399,
					reward: 3,
				},
				purchase_type: {
					type: 'purchase_types',
					id: '1',
					numerical_id: 1,
					is_recurring: false,
					name: 'Alquiler 48H',
					label: 'ALQUILER 48H',
					kind: 'rental',
					expires_after_in_seconds: 172800,
					available_time_in_seconds: 172800,
				},
				video_quality: {
					type: 'video_qualities',
					id: 'HD',
					numerical_id: 1,
					name: 'HD',
					abbr: 'HD',
					position: 1,
					image: 'https://images-0.wuaki.tv/system/logos/1/original/hd-1456155687.png',
				},
				external_tiers: [
					{
						type: 'microsoft_store',
						id: '9P30JJT99V5D',
						price: '4,49 €',
					},
					{
						type: 'itunes',
						id: 'tv.wuaki.alternatetier3',
						price: '3,99 €',
					},
				],
				warnings: [],
				order_option_display_info: {},
			},
			{
				type: 'order_options',
				id: '644888',
				numerical_id: 644888,
				legacy_instance_type: null,
				legacy_instance_id: null,
				periodic_points_reward_amount: 0,
				price: '3,99 €',
				price_without_currency: 3.99,
				points: {
					cost: 399,
					reward: 3,
				},
				purchase_type: {
					type: 'purchase_types',
					id: '1',
					numerical_id: 1,
					is_recurring: false,
					name: 'Alquiler 48H',
					label: 'ALQUILER 48H',
					kind: 'rental',
					expires_after_in_seconds: 172800,
					available_time_in_seconds: 172800,
				},
				video_quality: {
					type: 'video_qualities',
					id: 'UHD',
					numerical_id: 3,
					name: 'UHD',
					abbr: 'UHD',
					position: 3,
					image: 'https://images-3.wuaki.tv/system/logos/3/original/uhd-1437376240.png',
				},
				external_tiers: [
					{
						type: 'microsoft_store',
						id: '9P30JJT99V5D',
						price: '4,49 €',
					},
					{
						type: 'itunes',
						id: 'tv.wuaki.alternatetier3',
						price: '3,99 €',
					},
				],
				warnings: [
					{
						field: 'video_quality',
						code: 'warning.order_option.unable_to_play_in_this_device',
						message:
							'En este dispositivo no puedes reproducir esta calidad de vídeo, pero puedes disfrutarlo a través de otros de nuestros dispositivos compatibles',
					},
				],
				order_option_display_info: {},
			},
			{
				type: 'order_options',
				id: '473349',
				numerical_id: 473349,
				legacy_instance_type: null,
				legacy_instance_id: null,
				periodic_points_reward_amount: 0,
				price: '12,99 €',
				price_without_currency: 12.99,
				points: {
					cost: 1299,
					reward: 12,
				},
				purchase_type: {
					type: 'purchase_types',
					id: '2',
					numerical_id: 2,
					is_recurring: false,
					name: 'Venta (Digital Locker)',
					label: 'VENTA (DIGITAL LOCKER)',
					kind: 'purchase',
					expires_after_in_seconds: null,
					available_time_in_seconds: null,
				},
				video_quality: {
					type: 'video_qualities',
					id: 'SD',
					numerical_id: 2,
					name: 'SD',
					abbr: 'SD',
					position: 0,
					image: 'https://images-1.wuaki.tv/system/logos/2/original/sd-1456155688.png',
				},
				external_tiers: [
					{
						type: 'microsoft_store',
						id: '9N4VHH526N01',
						price: '12,99 €',
					},
					{
						type: 'itunes',
						id: 'tv.wuaki.tier12',
						price: '12,99 €',
					},
				],
				warnings: [],
				order_option_display_info: {},
			},
			{
				type: 'order_options',
				id: '473401',
				numerical_id: 473401,
				legacy_instance_type: null,
				legacy_instance_id: null,
				periodic_points_reward_amount: 0,
				price: '12,99 €',
				price_without_currency: 12.99,
				points: {
					cost: 1299,
					reward: 12,
				},
				purchase_type: {
					type: 'purchase_types',
					id: '2',
					numerical_id: 2,
					is_recurring: false,
					name: 'Venta (Digital Locker)',
					label: 'VENTA (DIGITAL LOCKER)',
					kind: 'purchase',
					expires_after_in_seconds: null,
					available_time_in_seconds: null,
				},
				video_quality: {
					type: 'video_qualities',
					id: 'HD',
					numerical_id: 1,
					name: 'HD',
					abbr: 'HD',
					position: 1,
					image: 'https://images-0.wuaki.tv/system/logos/1/original/hd-1456155687.png',
				},
				external_tiers: [
					{
						type: 'microsoft_store',
						id: '9N4VHH526N01',
						price: '12,99 €',
					},
					{
						type: 'itunes',
						id: 'tv.wuaki.tier12',
						price: '12,99 €',
					},
				],
				warnings: [],
				order_option_display_info: {},
			},
			{
				type: 'order_options',
				id: '473428',
				numerical_id: 473428,
				legacy_instance_type: null,
				legacy_instance_id: null,
				periodic_points_reward_amount: 0,
				price: '12,99 €',
				price_without_currency: 12.99,
				points: {
					cost: 1299,
					reward: 12,
				},
				purchase_type: {
					type: 'purchase_types',
					id: '2',
					numerical_id: 2,
					is_recurring: false,
					name: 'Venta (Digital Locker)',
					label: 'VENTA (DIGITAL LOCKER)',
					kind: 'purchase',
					expires_after_in_seconds: null,
					available_time_in_seconds: null,
				},
				video_quality: {
					type: 'video_qualities',
					id: 'UHD',
					numerical_id: 3,
					name: 'UHD',
					abbr: 'UHD',
					position: 3,
					image: 'https://images-3.wuaki.tv/system/logos/3/original/uhd-1437376240.png',
				},
				external_tiers: [
					{
						type: 'microsoft_store',
						id: '9N4VHH526N01',
						price: '12,99 €',
					},
					{
						type: 'itunes',
						id: 'tv.wuaki.tier12',
						price: '12,99 €',
					},
				],
				warnings: [
					{
						field: 'video_quality',
						code: 'warning.order_option.unable_to_play_in_this_device',
						message:
							'En este dispositivo no puedes reproducir esta calidad de vídeo, pero puedes disfrutarlo a través de otros de nuestros dispositivos compatibles',
					},
				],
				order_option_display_info: {},
			},
		],
		rating: {
			average: 5,
			scale: 5,
		},
		critic_reviews: {
			meta: {
				pagination: {
					page: 1,
					count: 0,
					per_page: 18,
					offset: 0,
					total_pages: 0,
				},
			},
			data: [],
		},
		user_reviews: {
			meta: {
				pagination: {
					page: 1,
					count: 1,
					per_page: 18,
					offset: 0,
					total_pages: 1,
				},
			},
			data: [
				{
					type: 'reviews',
					id: '50770',
					numerical_id: 50770,
					body:
						'"Los hermanos Wachowski hacen tan bien manteniendo la confusión sobre el complicado, inteligente y enigmático argumento, que la dificuldad del mismo no importa."',
					href: 'http://www.sensacine.com/peliculas/pelicula-19776/criticas-espectadores/',
					score: 9,
					person: {
						type: 'people',
						id: 'sensacine',
						numerical_id: 155604,
						photo: 'https://images-1.wuaki.tv/system/photos/155604/original/sensacine-1509727063.png',
						name: 'Sensacine',
						born_at: null,
					},
					source: {
						type: 'sources',
						id: '56',
						numerical_id: 56,
						name: 'Sensacine',
						url: 'http://www.sensacine.com/',
						score_scale: 10,
						logo: 'https://images-3.wuaki.tv/system/images/56/original/sensacine-1555059281.png',
					},
				},
			],
		},
		scores: [
			{
				type: 'scores',
				id: '128',
				numerical_id: 128,
				href: 'http://www.imdb.es/title/tt0133093/',
				amount_of_votes: null,
				formatted_amount_of_votes: null,
				score: 8.7,
				highlighted: false,
				site: {
					type: 'sites',
					id: '1',
					numerical_id: 1,
					name: 'IMDb',
					show_image: false,
					scale: 10,
					image: 'https://images-0.wuaki.tv/system/images/1/original/imdb-1481731825.png',
				},
			},
			{
				type: 'scores',
				id: '129',
				numerical_id: 129,
				href: 'http://www.filmaffinity.com/es/film932476.html',
				amount_of_votes: null,
				formatted_amount_of_votes: null,
				score: 7.9,
				highlighted: false,
				site: {
					type: 'sites',
					id: '2',
					numerical_id: 2,
					name: 'FilmAffinity',
					show_image: false,
					scale: 10,
					image: 'https://images-1.wuaki.tv/system/images/2/original/filmaffinity.png',
				},
			},
			{
				type: 'scores',
				id: '205404',
				numerical_id: 205404,
				href: 'https://www.themoviedb.org/movie/603',
				amount_of_votes: 14647,
				formatted_amount_of_votes: '14,6K',
				score: 8.1,
				highlighted: true,
				site: {
					type: 'sites',
					id: '40',
					numerical_id: 40,
					name: 'The Movie Database',
					show_image: false,
					scale: 10,
					image: 'https://images-1.wuaki.tv/system/images/40/original/the-movie-database-1488534910.png',
				},
			},
			{
				type: 'scores',
				id: '251882',
				numerical_id: 251882,
				href: 'http://www.sensacine.com/peliculas/pelicula-19776/',
				amount_of_votes: 4044,
				formatted_amount_of_votes: '4K',
				score: 7.24,
				highlighted: false,
				site: {
					type: 'sites',
					id: '56',
					numerical_id: 56,
					name: 'Sensacine',
					show_image: true,
					scale: 10,
					image: 'https://images-3.wuaki.tv/system/images/56/original/sensacine-1555059281.png',
				},
			},
		],
		subscription_plans: [],
		svod_schedules: [],
		tags: [],
		view_options: {
			support: {
				audio_qualities: [
					{
						type: 'audio_qualities',
						id: '2.0',
						numerical_id: 2,
						name: '2.0 (Stereo)',
						abbr: '2.0',
						image: 'https://images-1.wuaki.tv/system/logos/2/original/2-0-stereo-1456155689.png',
					},
				],
				video_qualities: [
					{
						type: 'video_qualities',
						id: 'HD',
						numerical_id: 1,
						name: 'HD',
						abbr: 'HD',
						position: 1,
						image: 'https://images-0.wuaki.tv/system/logos/1/original/hd-1456155687.png',
					},
					{
						type: 'video_qualities',
						id: 'SD',
						numerical_id: 2,
						name: 'SD',
						abbr: 'SD',
						position: 0,
						image: 'https://images-1.wuaki.tv/system/logos/2/original/sd-1456155688.png',
					},
				],
				hdr_types: [
					{
						type: 'hdr_types',
						id: 'NONE',
						numerical_id: 1,
						name: 'SDR',
						abbr: 'NONE',
						image: null,
					},
				],
			},
			public: {
				trailers: [
					{
						audio_languages: [
							{
								type: 'languages',
								id: 'SPA',
								numerical_id: 57,
								name: 'Español',
								abbr: 'SPA',
							},
						],
						subtitle_languages: [
							{
								type: 'languages',
								id: 'MIS',
								numerical_id: 1,
								name: 'Sin subtítulos',
								abbr: 'MIS',
							},
						],
						video_qualities: [
							{
								type: 'video_qualities',
								id: 'SD',
								numerical_id: 2,
								name: 'SD',
								position: 0,
								abbr: 'SD',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/sd-1456155688.png',
							},
						],
						audio_qualities: [
							{
								type: 'audio_qualities',
								id: '2.0',
								numerical_id: 2,
								name: '2.0 (Stereo)',
								abbr: '2.0',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/2-0-stereo-1456155689.png',
							},
						],
						streaming_drm_types: [
							{
								type: 'streaming_drm_types',
								id: 'PD-NONE',
							},
						],
						hdr_types: [
							{
								type: 'hdr_types',
								id: 'NONE',
								numerical_id: 1,
								name: 'SDR',
								abbr: 'NONE',
								image: null,
							},
						],
					},
					{
						audio_languages: [
							{
								type: 'languages',
								id: 'SPA',
								numerical_id: 57,
								name: 'Español',
								abbr: 'SPA',
							},
						],
						subtitle_languages: [
							{
								type: 'languages',
								id: 'MIS',
								numerical_id: 1,
								name: 'Sin subtítulos',
								abbr: 'MIS',
							},
						],
						video_qualities: [
							{
								type: 'video_qualities',
								id: 'UHD',
								numerical_id: 3,
								name: 'UHD',
								position: 3,
								abbr: 'UHD',
								image: 'https://images-3.wuaki.tv/system/logos/3/original/uhd-1437376240.png',
							},
						],
						audio_qualities: [
							{
								type: 'audio_qualities',
								id: '2.0',
								numerical_id: 2,
								name: '2.0 (Stereo)',
								abbr: '2.0',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/2-0-stereo-1456155689.png',
							},
						],
						streaming_drm_types: [
							{
								type: 'streaming_drm_types',
								id: 'DASH-NONE',
							},
						],
						hdr_types: [
							{
								type: 'hdr_types',
								id: 'NONE',
								numerical_id: 1,
								name: 'SDR',
								abbr: 'NONE',
								image: null,
							},
						],
					},
				],
				previews: [],
				adverts: [],
			},
			private: {
				streams: [
					{
						audio_languages: [
							{
								type: 'languages',
								id: 'DEU',
								numerical_id: 23,
								name: 'Alemán',
								abbr: 'DEU',
							},
							{
								type: 'languages',
								id: 'FRA',
								numerical_id: 21,
								name: 'Francés',
								abbr: 'FRA',
							},
							{
								type: 'languages',
								id: 'ITA',
								numerical_id: 32,
								name: 'Italiano',
								abbr: 'ITA',
							},
							{
								type: 'languages',
								id: 'SPA',
								numerical_id: 57,
								name: 'Español',
								abbr: 'SPA',
							},
						],
						subtitle_languages: [
							{
								type: 'languages',
								id: 'ENG',
								numerical_id: 18,
								name: 'Inglés',
								abbr: 'ENG',
							},
							{
								type: 'languages',
								id: 'NLD',
								numerical_id: 17,
								name: 'Holandés / Flamenco',
								abbr: 'NLD',
							},
							{
								type: 'languages',
								id: 'POR',
								numerical_id: 47,
								name: 'Portugués',
								abbr: 'POR',
							},
							{
								type: 'languages',
								id: 'SPA',
								numerical_id: 57,
								name: 'Español',
								abbr: 'SPA',
							},
							{
								type: 'languages',
								id: 'ITA',
								numerical_id: 32,
								name: 'Italiano',
								abbr: 'ITA',
							},
							{
								type: 'languages',
								id: 'DEU',
								numerical_id: 23,
								name: 'Alemán',
								abbr: 'DEU',
							},
							{
								type: 'languages',
								id: 'FRA',
								numerical_id: 21,
								name: 'Francés',
								abbr: 'FRA',
							},
							{
								type: 'languages',
								id: 'DAN',
								numerical_id: 16,
								name: 'Danés',
								abbr: 'DAN',
							},
							{
								type: 'languages',
								id: 'FIN',
								numerical_id: 20,
								name: 'Finés',
								abbr: 'FIN',
							},
							{
								type: 'languages',
								id: 'NOR',
								numerical_id: 44,
								name: 'Noruego',
								abbr: 'NOR',
							},
							{
								type: 'languages',
								id: 'SWE',
								numerical_id: 58,
								name: 'Sueco',
								abbr: 'SWE',
							},
							{
								type: 'languages',
								id: 'MIS',
								numerical_id: 1,
								name: 'Sin subtítulos',
								abbr: 'MIS',
							},
						],
						video_qualities: [
							{
								type: 'video_qualities',
								id: 'HD',
								numerical_id: 1,
								name: 'HD',
								position: 1,
								abbr: 'HD',
								image: 'https://images-0.wuaki.tv/system/logos/1/original/hd-1456155687.png',
							},
							{
								type: 'video_qualities',
								id: 'SD',
								numerical_id: 2,
								name: 'SD',
								position: 0,
								abbr: 'SD',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/sd-1456155688.png',
							},
						],
						audio_qualities: [
							{
								type: 'audio_qualities',
								id: '2.0',
								numerical_id: 2,
								name: '2.0 (Stereo)',
								abbr: '2.0',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/2-0-stereo-1456155689.png',
							},
						],
						streaming_drm_types: [
							{
								type: 'streaming_drm_types',
								id: 'PD-WVN',
							},
							{
								type: 'streaming_drm_types',
								id: 'DASH-CENC',
							},
							{
								type: 'streaming_drm_types',
								id: 'SS-PR',
							},
						],
						hdr_types: [
							{
								type: 'hdr_types',
								id: 'NONE',
								numerical_id: 1,
								name: 'SDR',
								abbr: 'NONE',
								image: null,
							},
						],
					},
					{
						audio_languages: [
							{
								type: 'languages',
								id: 'ENG',
								numerical_id: 18,
								name: 'Inglés',
								abbr: 'ENG',
							},
						],
						subtitle_languages: [
							{
								type: 'languages',
								id: 'ENG',
								numerical_id: 18,
								name: 'Inglés',
								abbr: 'ENG',
							},
							{
								type: 'languages',
								id: 'NLD',
								numerical_id: 17,
								name: 'Holandés / Flamenco',
								abbr: 'NLD',
							},
							{
								type: 'languages',
								id: 'POR',
								numerical_id: 47,
								name: 'Portugués',
								abbr: 'POR',
							},
							{
								type: 'languages',
								id: 'SPA',
								numerical_id: 57,
								name: 'Español',
								abbr: 'SPA',
							},
							{
								type: 'languages',
								id: 'ITA',
								numerical_id: 32,
								name: 'Italiano',
								abbr: 'ITA',
							},
							{
								type: 'languages',
								id: 'DEU',
								numerical_id: 23,
								name: 'Alemán',
								abbr: 'DEU',
							},
							{
								type: 'languages',
								id: 'FRA',
								numerical_id: 21,
								name: 'Francés',
								abbr: 'FRA',
							},
							{
								type: 'languages',
								id: 'DAN',
								numerical_id: 16,
								name: 'Danés',
								abbr: 'DAN',
							},
							{
								type: 'languages',
								id: 'FIN',
								numerical_id: 20,
								name: 'Finés',
								abbr: 'FIN',
							},
							{
								type: 'languages',
								id: 'NOR',
								numerical_id: 44,
								name: 'Noruego',
								abbr: 'NOR',
							},
							{
								type: 'languages',
								id: 'SWE',
								numerical_id: 58,
								name: 'Sueco',
								abbr: 'SWE',
							},
							{
								type: 'languages',
								id: 'MIS',
								numerical_id: 1,
								name: 'Sin subtítulos',
								abbr: 'MIS',
							},
						],
						video_qualities: [
							{
								type: 'video_qualities',
								id: 'HD',
								numerical_id: 1,
								name: 'HD',
								position: 1,
								abbr: 'HD',
								image: 'https://images-0.wuaki.tv/system/logos/1/original/hd-1456155687.png',
							},
							{
								type: 'video_qualities',
								id: 'SD',
								numerical_id: 2,
								name: 'SD',
								position: 0,
								abbr: 'SD',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/sd-1456155688.png',
							},
						],
						audio_qualities: [
							{
								type: 'audio_qualities',
								id: '2.0',
								numerical_id: 2,
								name: '2.0 (Stereo)',
								abbr: '2.0',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/2-0-stereo-1456155689.png',
							},
						],
						streaming_drm_types: [
							{
								type: 'streaming_drm_types',
								id: 'PD-WVN',
							},
							{
								type: 'streaming_drm_types',
								id: 'DASH-CENC',
							},
							{
								type: 'streaming_drm_types',
								id: 'SS-PR',
							},
						],
						hdr_types: [
							{
								type: 'hdr_types',
								id: 'NONE',
								numerical_id: 1,
								name: 'SDR',
								abbr: 'NONE',
								image: null,
							},
						],
					},
				],
				offline_streams: [
					{
						audio_languages: [
							{
								type: 'languages',
								id: 'ENG',
								numerical_id: 18,
								name: 'Inglés',
								abbr: 'ENG',
							},
						],
						subtitle_languages: [
							{
								type: 'languages',
								id: 'ENG',
								numerical_id: 18,
								name: 'Inglés',
								abbr: 'ENG',
							},
							{
								type: 'languages',
								id: 'NLD',
								numerical_id: 17,
								name: 'Holandés / Flamenco',
								abbr: 'NLD',
							},
							{
								type: 'languages',
								id: 'POR',
								numerical_id: 47,
								name: 'Portugués',
								abbr: 'POR',
							},
							{
								type: 'languages',
								id: 'SPA',
								numerical_id: 57,
								name: 'Español',
								abbr: 'SPA',
							},
							{
								type: 'languages',
								id: 'ITA',
								numerical_id: 32,
								name: 'Italiano',
								abbr: 'ITA',
							},
							{
								type: 'languages',
								id: 'DEU',
								numerical_id: 23,
								name: 'Alemán',
								abbr: 'DEU',
							},
							{
								type: 'languages',
								id: 'FRA',
								numerical_id: 21,
								name: 'Francés',
								abbr: 'FRA',
							},
							{
								type: 'languages',
								id: 'DAN',
								numerical_id: 16,
								name: 'Danés',
								abbr: 'DAN',
							},
							{
								type: 'languages',
								id: 'FIN',
								numerical_id: 20,
								name: 'Finés',
								abbr: 'FIN',
							},
							{
								type: 'languages',
								id: 'NOR',
								numerical_id: 44,
								name: 'Noruego',
								abbr: 'NOR',
							},
							{
								type: 'languages',
								id: 'SWE',
								numerical_id: 58,
								name: 'Sueco',
								abbr: 'SWE',
							},
							{
								type: 'languages',
								id: 'MIS',
								numerical_id: 1,
								name: 'Sin subtítulos',
								abbr: 'MIS',
							},
						],
						video_qualities: [
							{
								type: 'video_qualities',
								id: 'SD',
								numerical_id: 2,
								name: 'SD',
								position: 0,
								abbr: 'SD',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/sd-1456155688.png',
							},
						],
						audio_qualities: [
							{
								type: 'audio_qualities',
								id: '2.0',
								numerical_id: 2,
								name: '2.0 (Stereo)',
								abbr: '2.0',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/2-0-stereo-1456155689.png',
							},
						],
						streaming_drm_types: [
							{
								type: 'streaming_drm_types',
								id: 'PD-CENC',
							},
						],
						hdr_types: [
							{
								type: 'hdr_types',
								id: 'NONE',
								numerical_id: 1,
								name: 'SDR',
								abbr: 'NONE',
								image: null,
							},
						],
					},
					{
						audio_languages: [
							{
								type: 'languages',
								id: 'DEU',
								numerical_id: 23,
								name: 'Alemán',
								abbr: 'DEU',
							},
							{
								type: 'languages',
								id: 'FRA',
								numerical_id: 21,
								name: 'Francés',
								abbr: 'FRA',
							},
							{
								type: 'languages',
								id: 'SPA',
								numerical_id: 57,
								name: 'Español',
								abbr: 'SPA',
							},
							{
								type: 'languages',
								id: 'ITA',
								numerical_id: 32,
								name: 'Italiano',
								abbr: 'ITA',
							},
						],
						subtitle_languages: [
							{
								type: 'languages',
								id: 'ENG',
								numerical_id: 18,
								name: 'Inglés',
								abbr: 'ENG',
							},
							{
								type: 'languages',
								id: 'NLD',
								numerical_id: 17,
								name: 'Holandés / Flamenco',
								abbr: 'NLD',
							},
							{
								type: 'languages',
								id: 'POR',
								numerical_id: 47,
								name: 'Portugués',
								abbr: 'POR',
							},
							{
								type: 'languages',
								id: 'SPA',
								numerical_id: 57,
								name: 'Español',
								abbr: 'SPA',
							},
							{
								type: 'languages',
								id: 'ITA',
								numerical_id: 32,
								name: 'Italiano',
								abbr: 'ITA',
							},
							{
								type: 'languages',
								id: 'DEU',
								numerical_id: 23,
								name: 'Alemán',
								abbr: 'DEU',
							},
							{
								type: 'languages',
								id: 'FRA',
								numerical_id: 21,
								name: 'Francés',
								abbr: 'FRA',
							},
							{
								type: 'languages',
								id: 'DAN',
								numerical_id: 16,
								name: 'Danés',
								abbr: 'DAN',
							},
							{
								type: 'languages',
								id: 'FIN',
								numerical_id: 20,
								name: 'Finés',
								abbr: 'FIN',
							},
							{
								type: 'languages',
								id: 'NOR',
								numerical_id: 44,
								name: 'Noruego',
								abbr: 'NOR',
							},
							{
								type: 'languages',
								id: 'SWE',
								numerical_id: 58,
								name: 'Sueco',
								abbr: 'SWE',
							},
							{
								type: 'languages',
								id: 'MIS',
								numerical_id: 1,
								name: 'Sin subtítulos',
								abbr: 'MIS',
							},
						],
						video_qualities: [
							{
								type: 'video_qualities',
								id: 'SD',
								numerical_id: 2,
								name: 'SD',
								position: 0,
								abbr: 'SD',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/sd-1456155688.png',
							},
						],
						audio_qualities: [
							{
								type: 'audio_qualities',
								id: '2.0',
								numerical_id: 2,
								name: '2.0 (Stereo)',
								abbr: '2.0',
								image: 'https://images-1.wuaki.tv/system/logos/2/original/2-0-stereo-1456155689.png',
							},
						],
						streaming_drm_types: [
							{
								type: 'streaming_drm_types',
								id: 'PD-CENC',
							},
						],
						hdr_types: [
							{
								type: 'hdr_types',
								id: 'NONE',
								numerical_id: 1,
								name: 'SDR',
								abbr: 'NONE',
								image: null,
							},
						],
					},
				],
			},
		},
		additional_images: {},
		labels: {
			audio_qualities: [
				{
					type: 'audio_qualities',
					id: '2.0',
					numerical_id: 2,
					name: '2.0 (Stereo)',
					abbr: '2.0',
					image: 'https://images-1.wuaki.tv/system/logos/2/original/2-0-stereo-1456155689.png',
				},
			],
			hdr_types: [
				{
					type: 'hdr_types',
					id: 'NONE',
					numerical_id: 1,
					name: 'SDR',
					abbr: 'NONE',
					image: null,
				},
			],
			purchase_types: [
				{
					type: 'purchase_types',
					id: '1',
					numerical_id: 1,
					is_recurring: false,
					name: 'Alquiler 48H',
					label: 'ALQUILER 48H',
					kind: 'rental',
					expires_after_in_seconds: 172800,
					available_time_in_seconds: 172800,
				},
				{
					type: 'purchase_types',
					id: '2',
					numerical_id: 2,
					is_recurring: false,
					name: 'Venta (Digital Locker)',
					label: 'VENTA (DIGITAL LOCKER)',
					kind: 'purchase',
					expires_after_in_seconds: null,
					available_time_in_seconds: null,
				},
			],
			video_qualities: [
				{
					type: 'video_qualities',
					id: 'HD',
					numerical_id: 1,
					name: 'HD',
					abbr: 'HD',
					position: 1,
					image: 'https://images-0.wuaki.tv/system/logos/1/original/hd-1456155687.png',
				},
				{
					type: 'video_qualities',
					id: 'SD',
					numerical_id: 2,
					name: 'SD',
					abbr: 'SD',
					position: 0,
					image: 'https://images-1.wuaki.tv/system/logos/2/original/sd-1456155688.png',
				},
			],
		},
	},
};
